services:
  web-portfolio:
    image: ghcr.io/michimalek/web-portfolio:master
    container_name: web-portfolio
    restart: unless-stopped
    networks:
      - web-portfolio

networks:
  web-portfolio:
    driver: bridge
    name: web-portfolio